spring:
  application:
    name: apollo-configservice
  profiles:
    active: ${apollo_profile}

ctrip:
  appid: 100003171

server:
  port: 8080
logging:
  file: /Users/wanglijun/data/logs/100003171/apollo-configservice.log
